# Generated by Django 3.1.1 on 2020-10-14 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('prepare_finish_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='预计完成时间')),
                ('finished_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='实际完成时间')),
                ('done', models.BooleanField(default=False, verbose_name='完成')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
