# Generated by Django 3.1.1 on 2020-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished_time',
            field=models.DateTimeField(blank=True, max_length=64, null=True, verbose_name='实际完成时间'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prepare_finish_time',
            field=models.DateTimeField(max_length=64, verbose_name='预计完成时间'),
        ),
    ]
